/**
 * DCE Design Tokens — TypeScript port for SPFx consumption.
 *
 * In production this file is GENERATED by Style Dictionary from
 * `docs/sharepoint-pnp-spec/reference/dce-tokens.json` (per 06-tooling-pnp.md).
 * Do not edit by hand — change the JSON source and re-build.
 *
 * Pattern mirrored from
 *   /Users/tygranlund/dev/01-htt-brands/Convention-Page-Build/spfx/src/tokens/convention-tokens.ts
 * which exports a single `tokens` object consumed by all web parts.
 */

export const tokens = {
  color: {
    brand: {
      teal:         '#03534D',  // Official emerald · AAA on white 8.94:1
      tealDark:     '#02423D',  // Darker emerald for hover/active states
      tealDeeper:   '#062B28',  // Deep emerald hero backdrop
      tealLight:    '#3D817B',  // Decorative only on white
      tealOnDark:   '#75C7BE',  // Text/icons on dark surfaces
      gold:         '#D8A562',  // Official royal gold · decorative on white
      goldLight:    '#F0D7B4',
      goldDark:     '#6F4A1E',  // Dark gold for text/focus on light surfaces
      sage:         '#7A9B8A',  // Decorative
    },
    surface: {
      default: '#FAFAF7',
      dim:     '#F0EDE8',
      dark:    '#231F20',
      card:    '#FFFFFF',
    },
    text: {
      default:   '#231F20',   // Official almost-black · AAA on white/ivory
      secondary: '#465463',   // AAA on white 7.99:1
      muted:     '#8A96A4',   // AA Large only on white 3.53:1
      inverse:   '#F5F5F3',
    },
    textOnDark: {
      default: 'rgba(255, 255, 255, 0.92)',
      muted:   'rgba(255, 255, 255, 0.70)',
      subtle:  'rgba(255, 255, 255, 0.62)',
    },
    state: {
      success: '#66BB6A',
      danger:  '#A51C16',
      warn:    '#FB8C00',
      neutral: '#B0BEC5',
    },
  },
  font: {
    family: {
      heading: "'Playfair Display', Georgia, serif",
      body:    "'Tenor Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      system:  "'Segoe UI Variable', system-ui, sans-serif",
    },
    size: {
      xs:   '0.75rem',
      sm:   '0.875rem',
      base: '1rem',
      md:   '1.125rem',
      lg:   '1.5rem',
      xl:   '2rem',
      xxl:  '2.5rem',
      hero: 'clamp(2.5rem, 5vw, 4rem)',
    },
    weight: { regular: 400, medium: 500, bold: 700 },
    lineHeight: { tight: 1.15, normal: 1.5, loose: 1.7 },
  },
  spacing: {
    s0: 0, s1: 4, s2: 8, s3: 12, s4: 16, s5: 24, s6: 32, s8: 48, s12: 80, s16: 120,
    sectionPad: 'clamp(80px, 12vh, 140px)',
    container: 1140,
    gap: 'clamp(16px, 3vw, 32px)',
  },
  motion: {
    easeOut:    'cubic-bezier(0.22, 1, 0.36, 1)',
    easeSpring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    durationFast:    '0.2s',
    durationDefault: '0.7s',
  },
  breakpoint: { mobile: 640, tablet: 1023, compact: 1407 },
} as const;

export type DceTokens = typeof tokens;
